databases:
  - name: defaultdb
    plan: free
    databaseName: avnadmin
    user: avnadmin

services:
  - type: web
    plan: free
    name: avnadmin
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecomm_api_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: defaultdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4